### ISSUE TITLE
2.1 support?

### ISSUE THREAD

**Issue by alok** [glutanimate/cloze-overlapper#13]
Any plans/roadmap for it?

**Comment by glutanimate** [comment]
I'm currently working on porting Image Occlusion. Cloze Overlapper is next in line. My plan is to have all of my major add-ons ported to Anki 2.1 ready for the stable release (whose ETA is unknown at this point, but likely to be released this year).

**Comment by boydkelly** [comment]
I'm dying for this....  LOL.  Actually I have a highdpi screen and I just can't use 2.0 any longer.  I would need a magnifying glass to click on an icon.  But seriously great addon.  Looking forward to 2.1.  Thanks!

**Comment by qpwo** [comment]
Also hoping for 2.1 support!

**Comment by glutanimate** [comment]
Update: I'm closing in on [finishing the porting work on Review Heatmap](https://www.patreon.com/glutanimate/posts?tag=review-heatmap). Cloze Overlapper will be next.

**Comment by billpapadimas** [comment]
+1

**Comment by theGivingTree** [comment]
Does it work that generating cards from 2.0.x and only view cards on 2.1.x.
Thank you for your awesome work!

**Comment by emftech** [comment]
Hope you're still planning on porting that awesome add-on. I really miss it, it would really come in handy.

**Comment by ghc2018** [comment]
@glutanimate: Are there any Jabber-conferences or IRC channels to colaborate on porting? How about voice conferences even maybe?
I wish I could code in python, I will go for the tutorial and see.

**Comment by ghc2018** [comment]
Well, I created a group chat "MedAnki" in Jabber and with Conversations I am on there with my android mobile. It's just a start. MedAnki is medical memorization, had no better idea right now.

**Comment by zjosua** [comment]
Psst guys, look over [here](https://github.com/zjosua/cloze-overlapper).
It's not pretty and it's not backwards compatible, but it works for me.

> Well, I created a group chat "MedAnki" in Jabber and with Conversations I am on there with my android mobile. It's just a start. MedAnki is medical memorization, had no better idea right now.
> The group chat is in [kegolotajun@rooms.dismail.de](mailto:kegolotajun@rooms.dismail.de)

You might want to post this to [/r/medicalschoolanki](https://old.reddit.com/r/medicalschoolanki/) or even [/r/anki](https://old.reddit.com/r/anki/) to get some people on board.

**Comment by glutanimate** [comment]
Hey guys,

I'm happy to announce that the first alpha release of Cloze Overlapper v0.4.0 is finally ready for testing! This is the first release that implements Anki 2.1/2.0 compatibility, but it also comes with some [other significant changes](https://www.patreon.com/posts/cloze-overlapper-24279438). For a full list of the changes thus far please see the [changelog](https://github.com/glutanimate/cloze-overlapper/blob/master/CHANGELOG.md).

Pre-built zips are available on [my Patreon page](https://www.patreon.com/posts/cloze-overlapper-24385258) starting from now, but you may also simply grab a source archive from the [tags page](https://github.com/glutanimate/cloze-overlapper/tags) and build it yourself.

Thanks again for your patience over the past few months, everyone. I am sorry that this took so long, but I hope that – with a new solid base set – development will be able to move at a much more rapid pace from this point on.

Please do let me know if you run into any new issues with the alpha release.

@zjosua, thanks once again for helping me get the initial port off the ground and pushing me to finally get this thing done. I've added you to the credits screen of the add-on. Hope that's OK!

Best,
Glutanimate

**Comment by glutanimate** [comment]
@ghc2018 @zjosua I completely forgot that we actually have an anki dev channel on the [Anki Discord](https://discord.gg/JaB7QA)! It's never been very active, but it has picked up a bit of steam recently. Perhaps that might be a good place to coordinate stuff. For all of its faults, Discord does have a very low barrier of entry which could be helpful in getting more devs on board.

**Comment by JakubKoralewski** [comment]
@glutanimate Hey, so what's up? 😅

**Comment by mehdiwallden** [comment]
how's it going @glutanimate, how much money do you need XD :)

**Comment by rkmcdonnell** [comment]
@glutanimate Any timeline on pushing a public 2.1-compatible release?
