### ISSUE TITLE
Not generating continuous cloze captions

### ISSUE THREAD

**Issue by Elijahekc** [glutanimate/cloze-overlapper#14]
After reinstalling Anki with the Cloze overlapper plug-in, I am not able to generate multiple close captions (oc1, oc2, etc.) Instead both the shortcut Ctrl-Shift-C and the generate caption button on the toolbar are only generating {{c1::}} captions.
![screen shot 2018-04-03 at 19 29 54](https://user-images.githubusercontent.com/38050010/38268229-79b085be-3775-11e8-8743-d719160e4a19.png)

**Comment by glutanimate** [comment]
Hi. Thanks for the report. Could you please post a screenshot of all the add-ons you currently have installed in Anki?

**Comment by Elijahekc** [comment]
![screen shot 2018-04-03 at 19 55 21](https://user-images.githubusercontent.com/38050010/38269676-0e3d37b0-3779-11e8-80bb-562f9e801a20.png)

**Comment by glutanimate** [comment]
The issue is most likely caused by [Cloze Deletion Single Card](https://ankiweb.net/shared/info/1392166854). Please uninstall it and try again.

**Comment by Elijahekc** [comment]
Problem solved, thank you.

**Comment by glutanimate** [comment]
Happy to hear that. Enjoy using the add-on!
