### ISSUE TITLE
Cloze overlapping for "Strip HTML when pasting text"

### ISSUE THREAD

**Issue by maz1234** [glutanimate/cloze-overlapper#19]
Hi,

I'm trying to use cloze overlapping under the preference "Strip HTML when pasting text", but when I try to do this I get a message stating there are too many Cloze overlaps generated. I use the "Strip HTML when pasting text" preference because it allows me to copy and paste with the original formatting from Microsoft word (i.e. with colour etc). Is there anything I can do to be able to use Cloze Overlapping with the "Strip HTML when pasting text" preference?

**Comment by glutanimate** [comment]
Hi maz,

This is coming a bit late, but in case you're still wondering about the strip HTML option: When you have this disabled, what Anki does is paste a lot of complex HTML code into your fields. This allows you to preserve your formatting from Word, however all of these extra HTML tags confuse the automated cloze generator.

So my recommendation would be to switch to manually clozing items, instead. This works just the same as with regular clozes: You select a portion of text, then use the Ctrl+Shift+C hotkey to apply your cloze markers to it. In contrast to the automated cloze generator this should also work when having a bunch of formatting present, as is the case when the Strip HTML option is disabled.

Hope that helps!

Closing this in favor of #5.
