### ISSUE TITLE
Wrong tool tip for "Don't generate full cloze"

### ISSUE THREAD

**Issue by dgbeecher** [glutanimate/cloze-overlapper#2]
Small issue: the tool tip for "Don't generate full cloze" in the Overlapping Cloze Note Settings seems to be wrong. (It's identical to what I see when hovering my mouse over "No cues for first item".)

My mouse disappeared from the screenshot, but I was hovering over "Don't generate full cloze".

![timed-05_17_17 at 09 06 23pm](https://cloud.githubusercontent.com/assets/4223423/26182264/0425fb30-3b45-11e7-9669-87982df87395.png)

**Comment by glutanimate** [comment]
Hey @dgbeecher,

thanks for the heads-up! I'll fix this for the next release.
