### ISSUE TITLE
.ankiaddon is nowhere to be found

### ISSUE THREAD

**Issue by Undeadlol1** [glutanimate/cloze-overlapper#26]
#### Problem description
As readme state, i must drag-and-drop .ankiapp into addons list. Sadly i cannot find a file or folder with that name in latest realeas of thia addon.
![image](https://user-images.githubusercontent.com/4124323/59147232-84965580-8a12-11e9-8164-593bc171bf12.png)
![image](https://user-images.githubusercontent.com/4124323/59147234-88c27300-8a12-11e9-8301-43bccd6a036b.png)

Obviously, dragging and dropping this folder doesnt work in addons list.
I also tried to paste this files into "addons" folder on my pc. It didn't work either.
![image](https://user-images.githubusercontent.com/4124323/59147248-adb6e600-8a12-11e9-868b-922329617199.png)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
Anki 2.1.13 (3ba55990) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=False sv=1

Add-ons:

Edit Field During Review (disabled)
Right Hand Reviews jkl (disabled)
ImageResizer (disabled)
Syntax Highlighting for Code (disabled)
Night Mode (disabled)
Autosync 21 (disabled)
AnkiConnect (disabled)
Automatic Basic to Cloze (disabled)
Fast cards reposition (disabled)
Deck name in title 21 (disabled)
Life Drain (disabled)
cloze_overlapper
review_heatmap (disabled)
```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: Windows 10
- version:

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*
![image](https://user-images.githubusercontent.com/4124323/59147223-4731c800-8a12-11e9-9056-43239aae5318.png)

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

![image](https://user-images.githubusercontent.com/4124323/59147226-59ac0180-8a12-11e9-86b4-44dadd014593.png)

**Comment by glutanimate** [comment]
Hi Mihail. Thanks for the very detailed and thorough bug report!

The test releases are currently limited to my Patreon supporters as part of the early access program: https://www.patreon.com/glutanimate/posts?tag=Cloze%20Overlapper

Once testing is complete, and the 2.1 build sufficiently stable, I will be releasing the compiled builds on here and on AnkiWeb. However, you can also build the add-on yourself by following the build instructions in the README.

In any case, I've updated the README to make the installation instructions clearer (308c0b373bbf01cd373e87e1b55dc1f4d23c28c1).

**Comment by Undeadlol1** [comment]
Thank for your work. Much appreciated.

**Comment by Undeadlol1** [comment]
Also, i think i had a stroke when i was writing this report.

**Comment by glutanimate** [comment]
Thanks for the kind words :)

Yeah, the questionnaire is a bit exhaustive. For future reference: Feel free to leave out some of the sections if you feel they are unnecessary. The template is more of a guideline to help users who aren't that familiar with the general structure of a bug report.
