### ISSUE TITLE
Error building from source

### ISSUE THREAD

**Issue by edoreld** [glutanimate/cloze-overlapper#29]
#### Problem description

I read [on here](https://github.com/glutanimate/cloze-overlapper/issues/13) that you could build the addon from source, so I downloaded v0.4.0-alpha.0 from the [tags page](https://github.com/glutanimate/cloze-overlapper/tags). Then I ran make on the root directory. Instead of building the addons, it returned some errors.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [N/A] I've restarted Anki to see if it helps
 - [N/A] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [N/A] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [N/A] I've tried to disable other add-ons to see if there are any interactions present
 - [N/A] My issue disappears when I hold shift while starting Anki.
 - [X] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
Anki 2.1.11 (3cf770c7) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.13.6
Flags: frz=True ao=True sv=1

Add-ons:

Image Occlusion Enhanced for Anki 21 alpha
load balancer
Deck Stats
Anki Habitica for 21
AnkiConnect
Progress Bar
Card Info During Review
Button Colours Good Again
Japanese Support
Allows empty first field during adding and import
Life Drain
Polar Connect - PDF and Incremental Reading with Anki Sync
MorphMan for Anki 21
Review Heatmap
```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: macOS High Sierra
- version: 10.13.6

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

![image](https://user-images.githubusercontent.com/973854/60867065-3ef3c500-a22a-11e9-8804-9a17861e1db1.png)

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
rm -rf build
find . \( -name '*.pyc' -o -name '*.pyo' -o -name '__pycache__' \) -delete
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
# Create build directory
mkdir -p build/dist build/dist21
# Remove existing release build of same version
rm -f *-release--anki2*.zip
# Create a git snapshot of source files at  tag
git archive --format tar  | tar -x -C build/dist/
usage: git archive [<options>] <tree-ish> [<path>...]
   or: git archive --list
   or: git archive --remote <repo> [--exec <cmd>] [<options>] <tree-ish> [<path>...]
   or: git archive --remote <repo> [--exec <cmd>] --list

    --format <fmt>        archive format
    --prefix <prefix>     prepend prefix to each pathname in the archive
    -o, --output <file>   write the archive to this file
    --worktree-attributes
                          read .gitattributes in working directory
    -v, --verbose         report archived files on stderr
    -0                    store only
    -1                    compress faster
    -9                    compress better

    -l, --list            list supported archive formats

    --remote <repo>       retrieve the archive from remote repository <repo>
    --exec <command>      path to the remote git-upload-archive command

# Copy licenses to module directory
for license in build/dist/LICENSE* build/dist/resources/LICENSE*; do \
		[[ ! -f "$license" ]] && continue ; \
		name=$(basename $license) ; \
		ext="${name##*.}" ; \
		fname="${name%.*}" ; \
		echo "build/dist/src/cloze_overlapper/${fname}.txt" ; \
		cp $license "build/dist/src/cloze_overlapper/${fname}.txt" ; \
	done
# Include referenced assets that are not part of version control
[[ -d "resources/icons/optional" ]] && \
		 cp -r "resources/icons/optional" "build/dist/resources/icons/" || true
# Update credits if possible
type patreon_update_credits_addon >/dev/null 2>&1 && \
		cp addon.json build/dist/ && \
		cd build/dist && patreon_update_credits_addon -r || true
# Duplicate build folder for both build targets
cp -r build/dist/* build/dist21
cp: build/dist/*: No such file or directory
make: *** [buildarchive] Error 1
```

**Comment by glutanimate** [comment]
Please follow the instructions in the README: 

```
git clone https://github.com/glutanimate/cloze-overlapper.git
cd cloze-overlapper
aab build
```

To build a specific release, please see the instructions in `aab`'s README: https://github.com/glutanimate/anki-addon-builder/#usage
