### ISSUE TITLE
Sibling in 2.1

### ISSUE THREAD

**Issue by galantra** [glutanimate/cloze-overlapper#31]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### Your question

I know that clozes are treated as sibling in anki 2.0. Is this also true for anki 2.1?

**Comment by glutanimate** [comment]
Yes, Anki 2.1 also regards clozes crated from the same note as siblings.
