### ISSUE TITLE
Add-on "v0.4.0-alpha.0" failed to load in Anki 2.1

### ISSUE THREAD

**Issue by cmd8** [Glutanimate/cloze-overlapper#33]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

1. Clone repo
2. Run `aab build` in the root of the project
3. Add `cloze-overlapper-v0.4.0-alpha.0-anki21.ankiaddon` to Anki
4. Restart
5. Observe an error as shown in the screenshot at the bottom of the ticket

SHA of commits I tried to run `aab build` on:
- 9eabb6a
- 5909f3a

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

```
Version 2.1.14 (7b93e985)
Qt 5.12.1 PyQt 5.11.3
```

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
Anki 2.1.14 (7b93e985) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.14.5
Flags: frz=True ao=True sv=1

Add-ons:

Image Occlusion Enhanced for Anki 21 alpha
Hierarchical Tags Addon 20  21
Button Colours Good Again
True Retention
Cloze Overlapper
```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: macOS Mojave
- version: 10.14.5 (18F132)

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

![Screen Shot 2019-09-30 at 1 08 54 PM](https://user-images.githubusercontent.com/13213650/65841871-800bf900-e383-11e9-851a-6ba6823a8ef2.png)

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

![Screen Shot 2019-09-30 at 1 09 50 PM](https://user-images.githubusercontent.com/13213650/65841897-cb260c00-e383-11e9-9f10-fb3ff27e732f.png)

**Comment by acrognale** [comment]
I encountered the same issue-- installing PyQT5 via pip fixed it for me, i.e. `pip install pyqt5`

**Comment by glutanimate** [comment]
Thanks for chiming in @acrognale 

Right, `aab` needs to be run in an Anki development environment to work correctly, including access to the PyQT5 UI build tools.

See also here: https://github.com/glutanimate/anki-addon-builder/#installation

**Comment by 28andrew** [comment]
For future reference for those on Windows: 
- Make sure the Scripts folder of your python installation is in your path to allow access to PyQT5 UI build tools.
- Change the archive function in git.py of the aab package to:
```py
    def archive(self, version, outdir):
        logging.info("Exporting Git archive...")
        if not outdir or not version:
            return False
        
        outdir2 = str(outdir).replace('\\', '/')
        
        cmd = 'git archive --format tar {vers} | tar -x -C "{outdir}"'.format(
            vers=version, outdir=outdir2)
        return call_shell(cmd)
```
to fix spaces and Window's backslashes from making the command error
