### ISSUE TITLE
Cloze button generates Anki cloze markers rather than overlapping cloze markers

### ISSUE THREAD

**Issue by glutanimate** [Glutanimate/cloze-overlapper#34]
Using the cloze button will currently create Anki clozes (`{{c1::`) rather than the add-on's clozes (`[[oc1::]]`). This issue does not appear when using the cloze hotkeys.

(thanks to Gabriel for the report!)

**Comment by galantra** [comment]
I am getting this now with Ctrl+Shift+C as well. Am I the only one?

**Comment by josem8f** [comment]
Do you have by any chance the addon https://ankiweb.net/shared/info/24411424?
It has a copy of the code for clozes and overrides all others, happened to me, the pull request here is partially correct, I haven't found the "wrap2" method.

**Comment by galantra** [comment]
That was indeed the cause. Thank you, José!

**Comment by glutanimate** [comment]
Thanks for the reports, guys. Regarding the issue with Customize Keyboard Shortcuts: Updating to the latest version of CSB should fix things (cf. #45).

Regarding the original issue with the cloze button: I've fixed this in the current dev branch (not yet published on GitHub), so I'm closing the issue. The fix will land in the upcoming v1.0.0-alpha.1 release.
