### ISSUE TITLE
[Anki 2.0.52] AttributeError: '_Collection' object has no attribute 'schedVer' when rating an old card

### ISSUE THREAD

**Issue by aleksejrs** [Glutanimate/cloze-overlapper#39]
#### Problem description

Can't rate a card created with the previous Cloze Overlapper.
I updated the templates, only adding Text 21-36 and correcting the stylesheet accordingly.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```
Version 2.0.52
Qt 4.8.1 PyQt 4.9.1
```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: Debian GNU/Linux 10.3 stable+testing

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

Cloze Overlapper __version__ = "0.4.0-alpha.0"

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt/webview.py", line 21, in link
  File "aqt/reviewer.py", line 323, in _linkHandler
  File "aqt/reviewer.py", line 268, in _answerCard
  File "anki/sched.py", line 63, in answerCard
  File "anki/hooks.py", line 61, in repl
  File "/home/fc/.local/share/Anki2/addons/cloze_overlapper/sched.py", line 103, in myBurySiblings
    if mw.col.schedVer() == 1:
AttributeError: '_Collection' object has no attribute 'schedVer'```

**Comment by glutanimate** [comment]
Hi Aleksej,

Sorry for the super-late response. Unfortunately it looks like 0.4.0-alpha.0 was no longer compatible with Anki 2.0 already. I hadn't caught this because I've since dropped Anki 2.0 from my test array.

Because the code base has since moved on and 2.0 is no longer supported, I'm afraid I won't be able to provide a fix. However, if you want to fix this manually, you should be able to do so by replacing:

```python
        if mw.col.schedVer() == 1:
            self.col.db.execute(
                "update cards set queue=-2,mod=?,usn=? where id in " +
                ids2str(toBury),
                intTime(), self.col.usn())
            self.col.log(toBury)
        elif mw.col.schedVer() == 2:
            self.buryCards(toBury, manual=False)
```

in sched.py with:

```python
        self.col.db.execute(
            "update cards set queue=-2,mod=?,usn=? where id in " +
            ids2str(toBury),
            intTime(), self.col.usn())
        self.col.log(toBury)
```

My apologies again for the inconvenience!

**Comment by aleksejrs** [comment]
Well, thanks; but I already switched to 2.1.x for some reason, and am using 2.1.22.
