### ISSUE TITLE
Mathjax problem - false alert

### ISSUE THREAD

**Issue by p4nix** [Glutanimate/cloze-overlapper#41]
**Oops, it turns out it was the case of a dumb user. First of all, the problem also occured with regular clozes, and second, could be avoided by adding more whitespace around the < and >.**

#### Problem description

Trying to cloze overlap cards with Mathjax which include < and > symbols. Cloze overlapper shows them in the answer correctly when they are written out as `&lt;/&gt;` - but then they will be shown as error once "Reveal all clozes" is pressed - and basically vice versa.

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/7038116/78266137-a747ac80-7505-11ea-8373-d0806b6cfe53.png">

The issue persists when all add-ons are disabled (please forgive having them toggled on in the screenshot), it surely is some bug in note template.

Here is a test deck (*additionally* zipped because of Github, not a renamed apkg!):
[Default.apkg.zip](https://github.com/glutanimate/cloze-overlapper/files/4421949/Default.apkg.zip)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

Anki 2.1.23
Cloze Overlapper 0.40.0-alpha.0

Debug-Info:    
    Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
    Platform: Mac 10.15.4
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2020-04-02 15:43:11
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Anki Simulator ['anki_simulator', 2020-03-28T20:47, 'None', '']
    AwesomeTTS Google Cloud Text-to-Speech unofficial ['814349176', 2020-02-24T13:36, 'None', '']
    BetterTags ['bettertags', 2020-01-28T21:30, 'None', '']
    Cloze Overlapper ['cloze_overlapper', 2019-02-01T13:37, 'None', '']
    Customize Sidebar ['1988760596', 2020-01-28T11:44, 'None', '']
    Dancing Baloney Allows changing wallpapers with live preview ['378638814', 2020-03-27T06:28, 'None', mod]
    Frozen Fields ['516643804', 2020-03-01T05:12, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-01-16T13:36, 'None', '']
    ImageResizer ['1214357311', 2020-02-11T14:37, 'None', '']
    Puppy Reinforcement ['puppy_reinforcement', 2020-03-02T20:22, 'None', mod]
    Review Heatmap ['review_heatmap', 2018-10-28T23:06, 'None', '']
    Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2020-04-01T23:36, 'None', mod]
    Symbols As You Type ['2040501954', 2020-03-18T04:36, 'None', '']
    True Retention ['613684242', 2019-07-29T13:23, 'None', '']
    Visual Feedback for Reviews ['review_feedback', 2020-01-29T20:43, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1214357311 1374772155 1781298089 1988760596 2040501954 378638814 516643804 613684242 814349176
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AnkiWebView Inspector ['31746032', 2019-05-03T00:43, 'None', '']
    Extended Card Stats During Review ['1008566916', 2017-08-29T20:59, 'None', '']
    PDF Glossary Exporter ['pdf_glossary', 2019-08-19T14:35, 'None', '']
    Progress Bar ['2091361802', 2020-02-01T13:10, 'None', '']

**Comment by glutanimate** [comment]
Hey p4nix!

Thanks for the detailed report, and also for the follow-up! Please don't worry about this not being an issue with CO after all. This is still very helpful info in case another user runs into the same issue. So I definitely appreciate you posting here :)
