### ISSUE TITLE
When will this addon available for Anki 2.1?

### ISSUE THREAD

**Issue by Prashanth-BC** [Glutanimate/cloze-overlapper#44]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### Your question

*When will this addon available for Anki 2.1? I was able to build the addon using aab and install it. But I got errors after restarting Anki informing missing forms files*

**Comment by An-png** [comment]
Read this thread:
https://github.com/glutanimate/cloze-overlapper/issues/35#issuecomment-596125699
