### ISSUE TITLE
Does this work with 2.1.29 or 2.1.26?

### ISSUE THREAD

**Issue by PlEaSeH** [Glutanimate/cloze-overlapper#46]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ x] I've checked if anyone else asked this question before by looking through the issue reports.

#### Your question
I receive an error whenever I try to install it into my anki version :(

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.29 (bbff62bf) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-08-02 23:06:41

Caught exception:
Traceback (most recent call last):
  File "C:\Users\cuten\AppData\Roaming\Anki2\addons21\cloze_overlapper\gui\options_global.py", line 107, in onAccept
    config.save(reset=reset_req)
  File "C:\Users\cuten\AppData\Roaming\Anki2\addons21\cloze_overlapper\libaddon\anki\configmanager.py", line 219, in save
    saver(self._config[name])
  File "C:\Users\cuten\AppData\Roaming\Anki2\addons21\cloze_overlapper\libaddon\anki\configmanager.py", line 460, in _saveSynced
    self._getStorageObj("synced")[self._conf_key] = config
  File "lib\site-packages\anki\config.py", line 64, in __setitem__
  File "lib\site-packages\anki\config.py", line 40, in set
orjson.JSONEncodeError: Type is not JSON serializable: WrappedDict

**Comment by PlEaSeH** [comment]
I made it in aab just as the directions and it worked with anki 2.1.15, but not 2.1.26

**Comment by PlEaSeH** [comment]
Anki Add-on Builder v0.1.4

Copyright (C) 2016-2019  Aristotelis P. (Glutanimate)  <https://glutanimate.com>

This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions; For details please see the LICENSE file.

Getting Git version info...

=== Build task 1/1 ===

--- Building Cloze Overlapper v0.4.0-alpha.0 for anki21/local ---

Cleaning repository...
Exporting Git archive...
Copying licenses...
Copying changelog...
Writing manifest...
Building UI...
Starting UI build tasks for target 'anki21'...
Building files in 'build/dist/designer' to 'build/dist/src/cloze_overlapper/gui/forms/anki21' with 'pyuic5'
Building files in 'build/dist/resources' to 'build/dist/src/cloze_overlapper/gui/resources/anki21' with 'pyrcc5'
Cannot find file: icons/optional/coffee.svg
Cannot find file: icons/optional/patreon.svg
Cannot find file: icons/optional/twitter.svg
Cannot find file: icons/optional/youtube.svg
Done with all UI build tasks.
Packaging add-on...
Package saved as cloze-overlapper-v0.4.0-alpha.0-anki21.ankiaddon
Done.

This is how I built it

**Comment by glutanimate** [comment]
Hi @PlEaSeH,

It looks like your build went well, but the add-on currently suffers from some breakages introduced Anki 2.1.26 and 2.1.28 (cf. https://github.com/glutanimate/cloze-overlapper/milestone/2?closed=1). I've fixed these in an internal branch and am currently testing the changes. They should soon be published as v1.0.0-alpha.1. Until then I would recommend using Anki 2.1.22 if you can for the best-possible compatibility.

Closing this issue in favor of #48

**Comment by glutanimate** [comment]
(Thanks for taking the time to report this, BTW. Much appreciated, as always!)
