### ISSUE TITLE
Fix compatibility with Anki 2.1.28+

### ISSUE THREAD

**Issue by maejikal** [Glutanimate/cloze-overlapper#47]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*
I was trying to generate overlapping clozes with this add-on but however when i clicked on the button, an error shows up. I've done what Anki recommended which is to hold shift while starting anki. The problem does go away then but whenever i clicked on the button again, the same issue persists.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
Anki 2.1.28 (7d8818f8) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
Platform: Mac 10.15.5
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-05 19:12:20
Add-ons possibly involved: ⁨Cloze Overlapper⁩
```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: macOS
- version: 10.15.5 

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

<img width="384" alt="Screen Shot 2020-08-06 at 18 51 43" src="https://user-images.githubusercontent.com/69302838/89523932-44995100-d816-11ea-88f6-8b957a159dd7.png">

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.28 (7d8818f8) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
Platform: Mac 10.15.5
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-05 19:12:20
Add-ons possibly involved: ⁨Cloze Overlapper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 482, in handler
  File "aqt/editor.py", line 479, in <lambda>
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-12>", line 2, in _addCards
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File "/Users/meylingtr/Library/Application Support/Anki2/addons21/cloze_overlapper/editor.py", line 301, in onAddCards
    ret, total = overlapper.add()
  File "/Users/meylingtr/Library/Application Support/Anki2/addons21/cloze_overlapper/overlapper.py", line 117, in add
    self.updateNote(fields, full, setopts, custom)
  File "/Users/meylingtr/Library/Application Support/Anki2/addons21/cloze_overlapper/overlapper.py", line 203, in updateNote
    note.flush()
  File "anki/notes.py", line 67, in flush
AssertionError

```

**Comment by jimprince** [comment]
Also getting this error

**Comment by roysiu-gh** [comment]
Getting this too, version 2.1.30

**Comment by glutanimate** [comment]
Thanks for the reports, guys. Anki's behavior when adding notes changed between 2.1.26 and 2.1.28 which unfortunately resulted in this breakage (cf. also https://github.com/glutanimate/cloze-overlapper/issues/42 and  https://forums.ankiweb.net/t/assign-note-id-to-new-notes-in-addnote-window-revert-a-change-in-2-1-28/2354/2)

 I'm testing a fix internally at the moment that will land in the upcoming v1.0.0-alpha.1 release.
