### ISSUE TITLE
Creating New Card Bug

### ISSUE THREAD

**Issue by jeremyalexx** [Glutanimate/cloze-overlapper#49]
#### Problem description
Unable to complete any new "close overlapper" card types; prompted with error after completing all fields. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [X] I've restarted Anki to see if it helps
 - [X] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [X] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [X] I've tried to disable other add-ons to see if there are any interactions present
 - [X] My issue disappears when I hold shift while starting Anki.
 - [X] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.

##### If you are using Anki 2.1
Debug info:
Anki 2.1.28 (7d8818f8) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-10-21 15:34:29
Add-ons possibly involved: ⁨Cloze Overlapper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 482, in handler
  File "aqt/editor.py", line 479, in <lambda>
  File "/Users/alex/Library/Application Support/Anki2/addons21/cloze_overlapper/editor.py", line 154, in <lambda>
    editor.saveNow(lambda: callback(editor, *args, **kwargs))
  File "/Users/alex/Library/Application Support/Anki2/addons21/cloze_overlapper/editor.py", line 283, in onOlClozeButton
    return onFieldReady()
  File "/Users/alex/Library/Application Support/Anki2/addons21/cloze_overlapper/editor.py", line 270, in onFieldReady
    overlapper.add()
  File "/Users/alex/Library/Application Support/Anki2/addons21/cloze_overlapper/overlapper.py", line 117, in add
    self.updateNote(fields, full, setopts, custom)
  File "/Users/alex/Library/Application Support/Anki2/addons21/cloze_overlapper/overlapper.py", line 203, in updateNote
    note.flush()
  File "anki/notes.py", line 67, in flush
AssertionError

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: MacOS
- version: 10.15.6 (19G2021)

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*
![image](https://user-images.githubusercontent.com/68852840/90629534-b209a080-e25e-11ea-9858-d45bb8257439.png)
![image](https://user-images.githubusercontent.com/68852840/90629608-d36a8c80-e25e-11ea-9f2a-5766e1365a2a.png)

#### Error message (if any)
*If you've received an error message, please copy and paste it between the backticks below:*
![image](https://user-images.githubusercontent.com/68852840/90629879-3d833180-e25f-11ea-90ca-bace6ab63b7a.png)

**Comment by Farinata** [comment]
Same problem here.
(Anki 2.1.30 windows 10)

**Comment by PlEaSeH** [comment]
Cloze overlapper does not work with 2.1.26 and above and Glutanimate is working on a fix on version 1.0.0. :) For now, you would have to downgrade to Anki 2.1.22 to use Cloze overlapper.

**Comment by ghost** [comment]
I don't have this problem on mac 10.12.6, Anki 2.1.26.

**Comment by Farinata** [comment]
Any hope guys?!

**Comment by glutanimate** [comment]
Please see here, guys: #42

Fix is currently in testing.
