### ISSUE TITLE
(feature request) Add custom Cloze-overlapping  Note type

### ISSUE THREAD

**Issue by theGivingTree** [glutanimate/cloze-overlapper#6]
I want to configure custom styles per deck, but it seems not supported.
It would be quite useful to be able to add custom Note type for cloze overlapping.

**Comment by glutanimate** [comment]
You can setup additional note types by cloning the Cloze (overlapping) type
and adding the name of the cloned note type to the list of note types in
the add-on's settings menu. Make sure to separate it from the other entries
by a comma.

Am 25.08.2017 07:48 schrieb "Jinwook Jeong" <notifications@github.com>:

**Comment by theGivingTree** [comment]
Thank you for your answer
