### ISSUE TITLE
I want to make a card with only 1 cloze deletion

### ISSUE THREAD

**Issue by asdjung** [glutanimate/cloze-overlapper#9]
I understand this is made for memorizing an order but i want to use it how i use my regular cloze deletion for things that are not in order. I want to make a note with only 1 card can you help?

David
![screenshot_5](https://user-images.githubusercontent.com/33759887/32960025-862f2a0a-cbd4-11e7-80d3-bc9bc4916437.png)
![screenshot_1](https://user-images.githubusercontent.com/33759887/32960027-875ef9be-cbd4-11e7-8283-79b2bb7400a4.png)

**Comment by glutanimate** [comment]
Thanks for the suggestion!

This is [already implemented](https://github.com/glutanimate/cloze-overlapper/commit/b4bab091f3654c9543d7ed469ebdc6e3e83c28f1) in the current development branch. I mostly just have to find some time to do some additional testing before releasing a new version of the add-on on AnkiWeb.

I'll try to get a new beta release out over the winter break, so you should be able to give it a try soon.
